name: Triggering test from another repo
on: repository_dipsatch
types: [ my-event ]
jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -name: print-trigger-details
        run: |
          echo: ${{ github.event.client_payload.github.action }}
          echo: ${{ github.event.client_payload.github.actor }}
